### ISSUE TITLE
Rounding Issue in when assigning GQ HHs to Bzones

### ISSUE THREAD

**Issue by JoshRoll** [VisionEval/VisionEval#4] opened 2021-07-28 04:40 UTC
I'm new to posting issues so gonna get some of the conventions wrong but here is a go.  

We are testing the Albany VE-RSPM model using a different B zone structure and i was getting an error at the PredictHousing module.  I tracked it down to the block of code below and specified the inputs so you can test this and see if what i think is the issue is the problem.  

The code block below is where the issue is and i thought that by specifying at least 1 GQ in each bzone that would alleviate the issue but it seems that the round () function should allow for at least 1 decimal since the product of GQUnitDemand_Bx / sum(GQUnitDemand_Bx) if fed as a sampling probability which ends up being all zeros in this instance because the actual value of 0.4 is rounded down to all zeros thus producing the error.  

The other potential source of error might just be in the input that i am not aware of.  The previous bzone structure included 16 zones and we now have 40.  Below i specify the object GQUnitDemand <- 16 since that's what my L object returns but i think its supposed to be 40 but i can't figure what input is informing this element in the L object

```{r}
#Assign group quarters households to Bzones
  #------------------------------------------
  #Iterate through Azones to assign Bzones
#Commenting out  for (az in Az) {
    az <- "AAMPO"
    #Get inventory of group quarters units by Bzone
    #Comment this out GQUnits_Bx <- L$Year$Bzone$GQDU[L$Year$Bzone$Azone == az]
     GQUnits_Bx <- rep(1,40)
      #Comment this outBx <- L$Year$Bzone$Bzone[L$Year$Bzone$Azone == az]
     Bx <- paste("GEO", 1:40)
    names(GQUnits_Bx) <- Bx
    #Calculate demand
   #Commenting out  GQUnitDemand <- sum(IsGQ_Hh[L$Year$Household$Azone == az])
    GQUnitDemand <- 16 #Wondering if this is where the other possible issue is.  
    #Continue calculating if any GQ demand
    if (GQUnitDemand >= 1) {
      #If only one Bzone then all GQ households are in that Bzone
      if (length(Bx) == 1) {
        Bzone_Hx <- rep(Bx, GQUnitDemand)
        names(Bzone_Hx) <-
          L$Year$Household$HhId[IsGQ_Hh & L$Year$Household$Azone == az]
        Bzone_Hh[names(Bzone_Hx)] <- Bzone_Hx
      } else {
        #Scale Bzone demand to match overall demand
        GQUnitDemand_Bx <- round(GQUnitDemand * GQUnits_Bx / sum(GQUnits_Bx))
        UnitDiff <- GQUnitDemand - sum(GQUnitDemand_Bx)
        UnitDiff_By <-
          table(sample(Bx, abs(UnitDiff), replace = TRUE,
                       prob = GQUnitDemand_Bx / sum(GQUnitDemand_Bx)))
        GQUnitDemand_Bx[names(UnitDiff_By)] <-
          GQUnitDemand_Bx[names(UnitDiff_By)] + UnitDiff_By * sign(UnitDiff)
        #Assign group quarters units in Bzones to group quarters households
        Bzone_Hx <- sample(rep(Bx, GQUnitDemand_Bx))
        names(Bzone_Hx) <-
          L$Year$Household$HhId[IsGQ_Hh & L$Year$Household$Azone == az]
        Bzone_Hh[names(Bzone_Hx)] <- Bzone_Hx
      }
    }
  }

**Comment by dflynn-volpe** [comment] 2022-01-11 22:49
Hi Josh-- thanks for bringing this up.  It does look like it is a mismatch between `GQUnitDemand` and the `GQUnits_Bx`. It creates  a division by zero which is used in the sampling. We recently merged in a patch to a related issue for locating employment in Bzones, which was caused by zero-employment Bzones. See the latest [code over here](https://github.com/VisionEval/VisionEval-Dev). Is this still an issue?
Note that https://github.com/VisionEval/VisionEval-Dev/issues is the place to open issues -- so I'm going to close the issue here, and please feel free to re-open it in https://github.com/VisionEval/VisionEval-Dev/issues if this is still persisting.

**Closed by dflynn-volpe** 2022-01-11 22:49 UTC

**Comment by dflynn-volpe** [comment] 2022-01-11 22:51
After you take a look, we will disable the 'issues' feature here on VisionEval/VisionEval, so that it will be clear that VisionEval/VisionEval-Dev is the place to open them.
